spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/integraceferina/esp-back-i-parcial
          default-label: develop
          force-pull: true
          search-paths: config

server:
  port: ${PORT:8888}



    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
-data